// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCart = "cart"

// Cart mapped from table <cart>
type Cart struct {
	CartID    int32     `gorm:"column:cart_id;primaryKey" json:"cart_id"`
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`
	GoodsID   int32     `gorm:"column:goods_id;not null" json:"goods_id"`
	OrderID   int32     `gorm:"column:order_id;not null" json:"order_id"`
	Price     int32     `gorm:"column:price;not null" json:"price"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Cart's table name
func (*Cart) TableName() string {
	return TableNameCart
}
