// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	CommentID int32     `gorm:"column:comment_id;primaryKey" json:"comment_id"`
	GoodsID   int32     `gorm:"column:goods_id;not null" json:"goods_id"`
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`
	Desc      string    `gorm:"column:desc;not null" json:"desc"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
