// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCoupon = "coupon"

// Coupon mapped from table <coupon>
type Coupon struct {
	CouponID  int32     `gorm:"column:coupon_id;primaryKey" json:"coupon_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Satisfy   int32     `gorm:"column:satisfy;not null" json:"satisfy"`
	Minus     int32     `gorm:"column:minus;not null" json:"minus"`
	Desc      string    `gorm:"column:desc;not null" json:"desc"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Coupon's table name
func (*Coupon) TableName() string {
	return TableNameCoupon
}
