// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	OrderID       int32     `gorm:"column:order_id;primaryKey" json:"order_id"`
	UserID        int32     `gorm:"column:user_id;not null" json:"user_id"`
	MarkPrice     int32     `gorm:"column:mark_price;not null" json:"mark_price"`
	Price         int32     `gorm:"column:price;not null" json:"price"`
	DiscountPrice int32     `gorm:"column:discount_price;not null" json:"discount_price"`
	CouponID      int32     `gorm:"column:coupon_id;not null" json:"coupon_id"`
	Status        int32     `gorm:"column:status;not null" json:"status"`
	PayType       string    `gorm:"column:pay_type;not null" json:"pay_type"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
